/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"
#include <stdlib.h>

#include "led.h"
#include "uart.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	char ch[8];
	SystemInit();
	UartInit(BAUD_9600);
	LedInit(LED_BLUE);
	LedInit(LED_RED);
	UartPuts("Led-Uart Menu Driven\r\n");
		while(1)
			{
				UartPuts("Select Your Choice:\r\n1.Turn Red Led On.\r\n2.Turn Red Led Off\r\n3.Turn Blue Led On\r\n4.Turn Blue Led Off\r\nChoice:");
				UartGets(ch);
				int c = atoi(ch);
				while(c==0);
				switch(c)
					{
						case 1:
							LedOn(LED_RED);
							DelayMs(2000);
							break;
						case 2:
							LedOff(LED_RED);
							break;
						case 3:
							LedOn(LED_BLUE);
							DelayMs(2000);
							break;
						case 4:
							LedOff(LED_BLUE);
							break;
					}
			}

	return 0;
}
