/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"
#include "eeprom.h"
#include "uart.h"
#include "i2c.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	char str1[32]="DESD";
	char str[2];
	int choice;
	SystemInit();
	UartInit(BAUD_9600);
	UartPuts("Menu Driven Demo..!!!\r\n");
	UartPuts("Enter Choice\r\n");
	sscanf(str,"%d",&choice);
	UartGets(str);
	EEPROM_Init();
	while(1);
		switch(choice)
		{
			case 1:
				EEPROM_Write(0x0020, (uint8_t*)str1, 16);
				UartGets(str1);
				break;
			case 2:
				EEPROM_Read(0x0020,(uint8_t*)str1,16);
				UartPuts(str1);
				break;
		}

	return 0;
}
