/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"
#include "eeprom.h"
#include "uart.h"
#include "i2c.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{

	char ch[16];
	char str1[32];
	SystemInit();
	UartInit(BAUD_9600);
	EEPROM_Init();
	UartPuts("Menu Driven Demo..!!!\r\n");
	while(1)
	{
		UartPuts("Menu:\r\n1. Write a string into EEPROM\r\n2. Read 32 bytes from EEPROM\r\nEnter choice: ");
		UartGets(ch);
		int c = atoi(ch);
		switch(c)
		{
			case 1:
				UartPuts("Enter string to write into EEPROM: \r\n");
				UartGets(str1);
				UartPuts("String has been written succesfully...!!\r\n");
				EEPROM_Write(0x000, (uint8_t*)str1, strlen(str1));

				break;
			case 2:
				EEPROM_Read(0x0000,(uint8_t*)str1,32);
				UartPuts(str1);
				break;
		}
	}
	return 0;
}
